# Generated by Django 5.2.14 on 2026-05-21 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooks", "0001_initial"),
        ("menu", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dish_name", models.CharField(max_length=120)),
                ("meal_slot", models.CharField(max_length=20)),
                ("day_label", models.CharField(max_length=20)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("today", "Today")],
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("month_multiplier", models.PositiveIntegerField(default=1)),
                (
                    "cook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cooks.cookprofile",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="menu.dish"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
