# Generated by Django 5.2.14 on 2026-05-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
