# Generated by Django 5.2.14 on 2026-05-23 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_add_division_district_subdistrict"),
        ("orders", "0003_add_payment_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="locations.address",
            ),
        ),
    ]
