# Generated by Django 5.2.14 on 2026-05-23 12:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooks", "0002_add_capacity_per_day"),
        ("menu", "0001_initial"),
        ("orders", "0004_address_set_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDelivery",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dish_key",
                    models.CharField(
                        help_text="dishId::mealSlot composite key", max_length=200
                    ),
                ),
                ("date", models.DateField()),
                ("is_delivered", models.BooleanField(default=False)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "unique_together": {("order", "dish_key", "date")},
            },
        ),
        migrations.CreateModel(
            name="ProductionLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dish_key",
                    models.CharField(
                        help_text="dishId::mealSlot composite key", max_length=200
                    ),
                ),
                ("date", models.DateField()),
                (
                    "production_status",
                    models.CharField(default="pending", max_length=30),
                ),
                ("is_locked", models.BooleanField(default=False)),
                (
                    "cook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_logs",
                        to="cooks.cookprofile",
                    ),
                ),
                (
                    "dish",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu.dish",
                    ),
                ),
            ],
            options={
                "unique_together": {("cook", "dish_key", "date")},
            },
        ),
    ]
