# Generated by Django 5.2.14 on 2026-05-21 19:46

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cooks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=60)),
                (
                    "meal_slot",
                    models.CharField(
                        choices=[
                            ("Breakfast", "Breakfast"),
                            ("Lunch", "Lunch"),
                            ("Dinner", "Dinner"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "days",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("mon", "Mon"),
                                ("tue", "Tue"),
                                ("wed", "Wed"),
                                ("thu", "Thu"),
                                ("fri", "Fri"),
                                ("sat", "Sat"),
                                ("sun", "Sun"),
                            ],
                            max_length=3,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("capacity", models.PositiveIntegerField(default=0)),
                ("cutoff_time", models.TimeField()),
                ("image_url", models.URLField(blank=True, null=True)),
                (
                    "add_ons_label",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("available", models.BooleanField(default=True)),
                ("is_popular", models.BooleanField(default=False)),
                (
                    "cook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dishes",
                        to="cooks.cookprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WeeklyMenu",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("week_start", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_menus",
                        to="cooks.cookprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
