ORDER_CONFIRMED = "order.confirmed"
ORDER_PREPARING = "order.preparing"
ORDER_OUT_FOR_DELIVERY = "order.out_for_delivery"
ORDER_DELIVERED = "order.delivered"
ORDER_CANCELLED = "order.cancelled"
NEW_ORDER = "new_order"
