# Generated by Django 5.2.14 on 2026-05-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="district",
            field=models.CharField(default="Dhaka", max_length=50),
        ),
        migrations.AddField(
            model_name="address",
            name="division",
            field=models.CharField(default="Dhaka", max_length=50),
        ),
        migrations.AddField(
            model_name="address",
            name="sub_district",
            field=models.CharField(
                default="", help_text="e.g. Uttara, Banani, Gulshan", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="label",
            field=models.CharField(help_text="e.g. Home, Office", max_length=50),
        ),
        migrations.AlterField(
            model_name="address",
            name="line1",
            field=models.CharField(
                help_text="Exact address / house / road", max_length=255
            ),
        ),
    ]
