# Generated by Django 5.2.14 on 2026-05-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pin_hash",
            field=models.CharField(
                blank=True,
                help_text="Hashed 4-digit PIN for quick login",
                max_length=128,
                null=True,
            ),
        ),
    ]
