# Generated by Django 5.2.14 on 2026-05-21 19:46

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CookProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "cuisine_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "specialties",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("total_orders_count", models.PositiveIntegerField(default=0)),
                ("area_label", models.CharField(blank=True, max_length=120, null=True)),
                ("radius_km", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("coordinates", models.JSONField(blank=True, null=True)),
                ("holiday_mode_enabled", models.BooleanField(default=False)),
                (
                    "payout_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bkash", "bKash"),
                            ("nagad", "Nagad"),
                            ("card", "Card"),
                            ("bank", "Bank"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "payout_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "payout_account_name",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "available_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cook_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CookVerification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nid_front",
                    models.FileField(
                        blank=True, null=True, upload_to="verification/nid_front/"
                    ),
                ),
                (
                    "nid_back",
                    models.FileField(
                        blank=True, null=True, upload_to="verification/nid_back/"
                    ),
                ),
                (
                    "selfie",
                    models.FileField(
                        blank=True, null=True, upload_to="verification/selfie/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("pending_review", "Pending review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="unverified",
                        max_length=30,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cook_verification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PayoutAccount",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payout_method",
                    models.CharField(
                        choices=[
                            ("bkash", "bKash"),
                            ("nagad", "Nagad"),
                            ("card", "Card"),
                            ("bank", "Bank"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payout_number", models.CharField(max_length=30)),
                ("payout_account_name", models.CharField(max_length=120)),
                ("is_default", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
