# Generated by Django 5.2.14 on 2026-05-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookprofile",
            name="capacity_per_day",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Meals per day capacity", null=True
            ),
        ),
    ]
